---
  - name: Check the remote host Kernel version
    hosts: all
    tasks:
      - name: Execute the Uptime command over Command module
        register: unameoutput
        command: "uname -a"

      - debug:
          var: unameoutput.stdout_lines
